---
output:
  github_document: default
---
# `covdepGE:` Covariate Dependent Graph Estimation

## Installation

Run the following in `R`:

`devtools::install_github("JacobHelwig/covdepGE")`

## Overview

Suppose $\pmb{X}\in \mathbb{R}^{n\times p}$ is a data matrix of independent observations $\pmb{X} = \left(\pmb{x}_1,..., \pmb{x}_p\right)$ such that $\pmb{X}\sim\mathcal N(\mu, \Sigma)$. Then, using Gaussian graphical modeling techniques, the conditional dependence structure of $\pmb{x_1},...,\pmb{x_p}$ can be modeled as an undirected graph $\mathcal{G}$ such that:

$\hspace{7cm}\mathcal G_{i,j} = \mathbb I \left(\pmb{x_i}\bot\pmb{x_j}\quad\vert\{\pmb{x_1},\ldots,\pmb{x_p}\}\setminus\{\pmb{x_i, x_j}\}\right)$

That is, there is an edge between the $\pmb{x_i}$ and $\pmb{x_j}$ nodes if, and only if, these variables are dependent on each other given all other variables.
 
Let $\pmb{Z}$ be an $n\times p'$ matrix of extraneous covariates. Further suppose that the conditional dependence structure of $\pmb{X}$ is not homogeneous across the individuals, and is instead a continuous function of the extraneous covariates $\pmb Z$(1). Then, this methodology aims to estimate a graph for each of the individuals, possibly unique to the individual, such that similar estimates are made for those who are similar to one another in terms of the extraneous covariates. 
 
 For an example application, see (1), wherein the sample was composed of healthy and cancerous individuals, $\pmb x_1,...,\pmb x_8$ were protein expression levels of 8 genes, and $\pmb Z$ was the copy number variation of a gene $\pmb z$ associated with cancer, $\pmb z\not\in \{\pmb x_1,...,\pmb x_8\}$. 

## Functionality

The main function, `covdepGE::covdepGE(`$\pmb X,\pmb Z$`)`, estimates the posterior distribution of the graphical structure $\mathcal G_l$ for each of the $n$ individuals using a variational mean-field approximation. 

## Bibliography 

(1) Dasgupta S., Ghosh P., Pati D., Mallick B. “An approximate
Bayesian approach to covariate dependent graphical modeling." 2021

## Demo

```{r}
library(covdepGE)
library(ggplot2)

# get the data
set.seed(1)
data <- generate_continuous()
X <- data$data
Z <- data$covts
interval <- data$interval
prec <- data$true_precision

# get overall and within interval sample sizes
n <- nrow(X)
n1 <- sum(interval == 1)
n2 <- sum(interval == 2)

# visualize the distribution of the extraneous covariate
ggplot(data.frame(Z = Z, interval = as.factor(interval))) +
  geom_histogram(aes(Z, fill = interval), color = "black", bins = n %/% 5)

# visualize the true precision matrices in each of the intervals

# interval 1
matViz(prec[[1]], incl_val = T) + ggtitle("True precision matrix, interval 1")

# interval 2 (varies continuously with Z)
int2_mats <- prec[interval == 2]
int2_inds <- c(5, n2 %/% 2, n2 - 5)
lapply(int2_inds, function(j) matViz(int2_mats[[j]], incl_val = T) +
         ggtitle(paste("True precision matrix, interval 2, individual", j)))

# interval 3
matViz(prec[[length(prec)]], incl_val = T) +
  ggtitle("True precision matrix, interval 3")

# fit the model and visualize the estimated precision matrices
(out <- covdepGE(X, Z))
plot(out)

# visualize the posterior inclusion probabilities for variables (1, 3) and (1, 2)
inclusionCurve(out, 1, 2)
inclusionCurve(out, 1, 3)
```
