---
title: "Alpha sensitivity analysis"
output: pdf_document
---

```{r, include = F}
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 65), tidy = TRUE)
```

```{r}
library(covdepGE)
library(ggplot2)
library(latex2exp)
# function to create probability of inclusion visualization
gg_graph <- function(incl_probs, alpha) return(ggplot(reshape2::melt(incl_probs), aes(x=Var1, y=Var2, fill=value)) + geom_tile(color = "brown") + scale_fill_gradient(low = "white", high = "steelblue", breaks = c(1, 0)) + labs(fill="Probability of Inclusion") + theme_classic() + xlab("Variable") + ylab("Variable") + ggtitle(TeX(paste("Inclusion probabilities, individual 45, $\\alpha_0 = $", alpha))) + theme(plot.title = element_text(hjust = 0.5)))

source("generate_data.R") 
cont <- generate_continuous()

alpha_init <- seq(-1000, 1000, 200)

for (alpha in alpha_init){
  out.cont <- covdepGE(data_mat = cont$data,
                     Z = cont$covts,
                     tau = 0.56,
                     alpha = alpha,
                     pi_vec = NULL,
                     print_time = T)
  # get probabilities of inclusion for the 45th individual
  incl.probs.cont45 <- out.cont$inclusion_probs[[45]]

  print(gg_graph(incl.probs.cont45, alpha))
}

```
