---
title: "Large p small n"
output: pdf_document
---

# Run 1 and Run 2

```{r}
library(covdepGE)
library(ggplot2)

# get the data
set.seed(1)
data <- generateData(50, 10, 25, 10)
X <- data$data
Z <- data$covts
interval <- data$interval
prec <- data$true_precision

# get overall and within interval sample sizes
n <- nrow(X)
n1 <- sum(interval == 1)
n2 <- sum(interval == 2)

# visualize the distribution of the extraneous covariate
ggplot(data.frame(Z = Z, interval = as.factor(interval))) +
  geom_histogram(aes(Z, fill = interval), color = "black", bins = n %/% 5)

# visualize the true precision matrices in each of the intervals

# interval 1
cat("\n\nInterval 1: Observations", paste0(range(which(interval == 1)), collapse = ",...,"))
matViz(prec[[1]]) + ggtitle("True precision matrix, interval 1") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# interval 2 (varies continuously with Z)
cat("\n\nInterval 2: Observations", paste0(range(which(interval == 2)), collapse = ",...,"))
int2_mats <- prec[interval == 2]
int2_inds <- c(5, n2 %/% 2, n2 - 5)
lapply(int2_inds, function(j) matViz(int2_mats[[j]]) +
         ggtitle(paste("True precision matrix, interval 2, observation", j)) + 
         theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)))

# interval 3
cat("\n\nInterval 3: Observations", paste0(range(which(interval == 3)), collapse = ",...,"))
matViz(prec[[length(prec)]]) +
  ggtitle("True precision matrix, interval 3") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# fit the model and visualize the estimated precision matrices
(out <- covdepGE(X, Z, parallel = T, num_workers = 16))
plts <- plot(out)
lapply(plts, function(plt) plt + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)))
out$weights$bandwidths
summary(c(sapply(lapply(out$hyperparameters, `[[`, "grid"), `[[`, "pip")))
summary(c(sapply(lapply(out$hyperparameters, `[[`, "grid"), `[[`, "sbsq")))
summary(c(sapply(lapply(out$hyperparameters, `[[`, "grid"), `[[`, "ssq")))
sbsq <- seq(1e-5, 2, length.out = 5)
(out <- covdepGE(X, Z, pip_upper = 0.2, sbsq = sbsq, parallel = T, num_workers = 16))
plts <- plot(out)
lapply(plts, function(plt) plt + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)))
```

# Run 3

```{r}
# only one interval
data <- generateData(50, 45, 0, 0)
X <- data$data
Z <- data$covts
interval <- data$interval
prec <- data$true_precision

# get overall and within interval sample sizes
n <- nrow(X)
n1 <- sum(interval == 1)
n2 <- sum(interval == 2)

# visualize the distribution of the extraneous covariate
ggplot(data.frame(Z = Z, interval = as.factor(interval))) +
  geom_histogram(aes(Z, fill = interval), color = "black", bins = n %/% 5) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


# visualize the true precision matrices in each of the intervals

# interval 1
cat("\n\nInterval 1: Observations", paste0(range(which(interval == 1)), collapse = ",...,"))
matViz(prec[[1]]) + ggtitle("True precision matrix, interval 1")

# fit the model and visualize the estimated precision matrices
(out <- covdepGE(X, Z, parallel = T, num_workers = 16))
plts <- plot(out)
lapply(plts, function(plt) plt + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)))
```

# Run 4

```{r}
# get the data
set.seed(1)
data <- generateData(50)
X <- data$data
Z <- data$covts
interval <- data$interval
prec <- data$true_precision

# get overall and within interval sample sizes
n <- nrow(X)
n1 <- sum(interval == 1)
n2 <- sum(interval == 2)

# visualize the distribution of the extraneous covariate
ggplot(data.frame(Z = Z, interval = as.factor(interval))) +
  geom_histogram(aes(Z, fill = interval), color = "black", bins = n %/% 5)

# visualize the true precision matrices in each of the intervals

# interval 1
cat("\n\nInterval 1: Observations", paste0(range(which(interval == 1)), collapse = ",...,"))
matViz(prec[[1]]) + ggtitle("True precision matrix, interval 1") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# interval 2 (varies continuously with Z)
cat("\n\nInterval 2: Observations", paste0(range(which(interval == 2)), collapse = ",...,"))
int2_mats <- prec[interval == 2]
int2_inds <- c(5, n2 %/% 2, n2 - 5)
lapply(int2_inds, function(j) matViz(int2_mats[[j]]) +
         ggtitle(paste("True precision matrix, interval 2, observation", j)) + 
         theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)))

# interval 3
cat("\n\nInterval 3: Observations", paste0(range(which(interval == 3)), collapse = ",...,"))
matViz(prec[[length(prec)]]) +
  ggtitle("True precision matrix, interval 3") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# fit the model and visualize the estimated precision matrices
(out <- covdepGE(X, Z, parallel = T, num_workers = 16))
plts <- plot(out)
lapply(plts, function(plt) plt + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)))
```
