---
title: "Pi, sigmabeta_sq grid optimization"
output: pdf_document
---

```{r, include = F}
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 65), tidy = TRUE)
```

```{r}
library(covdepGE)
library(ggplot2)
source("generate_data.R") 
cont <- generate_continuous()
disc <- generate_discrete(same = F)

# continuous data using the value of pi obtained using CS
out.cont_CS <- covdepGE(data_mat = cont$data,
                        Z = cont$covts,
                        tau = 0.56,
                        sigmavec = c(0.01, 0.05, 0.1, 0.5, 1, 3, 7, 10),
                        pi_vec = NULL,
                        print_time = T)

# continuous data using a grid of pi values
out.cont_grid <- covdepGE(data_mat = cont$data,
                          Z = cont$covts,
                          tau = 0.56,
                          sigmavec = c(0.01, 0.05, 0.1, 0.5, 1, 3, 7, 10),
                          pi_vec = seq(from = 0.05, to = 0.95, by = 0.05),
                          print_time = T)

# ELBO from models using pi from CS
out.cont_CS$ELBO

# ELBO from models using pi from grid search 
out.cont_grid$ELBO

# compare the resulting ELBO
ELBO_CS <- unlist(lapply(out.cont_CS$ELBO, `[[`, 3))
ELBO_grid <- unlist(lapply(out.cont_grid$ELBO, `[[`, 3))
cbind.data.frame(ELBO_CS, ELBO_grid, difference = ELBO_grid - ELBO_CS)

# get probabilities of inclusion for the 45th and 135th individual
round(incl.probs.cont_CS45 <- out.cont_CS$inclusion_probs[[45]], 2)
round(incl.probs.cont_grid45 <- out.cont_grid$inclusion_probs[[45]], 2)

round(incl.probs.cont_CS135 <- out.cont_CS$inclusion_probs[[135]], 2)
round(incl.probs.cont_grid135 <- out.cont_grid$inclusion_probs[[135]], 2)

# get the true graphs for the 45th and 135th individual 
true.graph45 <- cont$true_graphs[[45]]
true.graph135 <- cont$true_graphs[[135]]

# visualize the probabilities of inclusion and true graphs

# true graph individual 45
(ggplot(reshape2::melt(true.graph45), aes(x=Var1, y=Var2, fill=value)) + geom_tile(color = "brown") + scale_fill_gradient(low = "white", high = "steelblue", breaks = c(1, 0)) + guides(fill=guide_legend(title="")) + theme_classic() + xlab("Variable") + ylab("Variable") + scale_x_continuous(breaks = seq(1, ncol(disc$data), 2)) + scale_y_continuous(breaks = seq(1, ncol(disc$data), 2)) + ggtitle("TRUE Graph for individual 45") + theme(plot.title = element_text(hjust = 0.5)))

# continuous individual 45, CS
(ggplot(reshape2::melt(incl.probs.cont_CS45), aes(x=Var1, y=Var2, fill=value)) + geom_tile(color = "brown") + scale_fill_gradient(low = "white", high = "steelblue", breaks = c(1, 0)) + labs(fill="Probability of Inclusion") + theme_classic() + xlab("Variable") + ylab("Variable") + ggtitle("Inclusion probabilities, individual 45, CS") + theme(plot.title = element_text(hjust = 0.5)))

# continuous individual 45, grid
(ggplot(reshape2::melt(incl.probs.cont_grid45), aes(x=Var1, y=Var2, fill=value)) + geom_tile(color = "brown") + scale_fill_gradient(low = "white", high = "steelblue", breaks = c(1, 0)) + labs(fill="Probability of Inclusion") + theme_classic() + xlab("Variable") + ylab("Variable") + ggtitle("Inclusion probabilities, individual 45, grid") + theme(plot.title = element_text(hjust = 0.5)))

# true graph individual 135
(ggplot(reshape2::melt(true.graph135), aes(x=Var1, y=Var2, fill=value)) + geom_tile(color = "brown") + scale_fill_gradient(low = "white", high = "steelblue", breaks = c(1, 0)) + guides(fill=guide_legend(title="")) + theme_classic() + xlab("Variable") + ylab("Variable") + scale_x_continuous(breaks = seq(1, ncol(disc$data), 2)) + scale_y_continuous(breaks = seq(1, ncol(disc$data), 2)) + ggtitle("TRUE Graph for individual 135") + theme(plot.title = element_text(hjust = 0.5)))

# continuous individual 135, CS
(ggplot(reshape2::melt(incl.probs.cont_CS135), aes(x=Var1, y=Var2, fill=value)) + geom_tile(color = "brown") + scale_fill_gradient(low = "white", high = "steelblue", breaks = c(1, 0)) + labs(fill="Probability of Inclusion") + theme_classic() + xlab("Variable") + ylab("Variable") + ggtitle("Inclusion probabilities, individual 135, CS") + theme(plot.title = element_text(hjust = 0.5)))

# continuous individual 135, grid
(ggplot(reshape2::melt(incl.probs.cont_grid135), aes(x=Var1, y=Var2, fill=value)) + geom_tile(color = "brown") + scale_fill_gradient(low = "white", high = "steelblue", breaks = c(1, 0)) + labs(fill="Probability of Inclusion") + theme_classic() + xlab("Variable") + ylab("Variable") + ggtitle("Inclusion probabilities, individual 135, grid") + theme(plot.title = element_text(hjust = 0.5)))

# discrete data using the value of pi obtained using CS
out.disc_CS <- covdepGE(data_mat = disc$data,
                        Z = disc$covts,
                        tau = 0.1,
                        sigmavec = c(0.01, 0.05, 0.1, 0.5, 1, 3, 7, 10),
                        pi_vec = NULL,
                        print_time = T)

# continuous data using a grid of pi values
out.disc_grid <- covdepGE(data_mat = disc$data,
                          Z = disc$covts,
                          tau = 0.1,
                          sigmavec = c(0.01, 0.05, 0.1, 0.5, 1, 3, 7, 10),
                          pi_vec = seq(from = 0.05, to = 0.95, by = 0.05),
                          print_time = T)

# ELBO from models using pi from CS
out.disc_CS$ELBO

# ELBO from models using pi from grid search 
out.disc_grid$ELBO

# compare the resulting ELBO
ELBO_CS <- unlist(lapply(out.disc_CS$ELBO, `[[`, 3))
ELBO_grid <- unlist(lapply(out.disc_grid$ELBO, `[[`, 3))
cbind.data.frame(ELBO_CS, ELBO_grid, difference = ELBO_grid - ELBO_CS)

# get probabilities of inclusion for covariate level 1 and 2
round(incl.probs.disc_CS1 <- out.disc_CS$inclusion_probs[[1]], 2)
round(incl.probs.disc_grid1 <- out.disc_grid$inclusion_probs[[1]], 2)

round(incl.probs.disc_CS2 <- out.disc_CS$inclusion_probs[[nrow(disc$data)]], 2)
round(incl.probs.disc_grid2 <- out.disc_grid$inclusion_probs[[nrow(disc$data)]], 2)

# get the true graphs for covariate level 1 and 2 
true.graph1 <- disc$true_graphs[[1]]
true.graph2 <- disc$true_graphs[[2]]

# visualize the probabilities of inclusion and true graphs

# true graph, covariate level 1
(ggplot(reshape2::melt(true.graph1), aes(x=Var1, y=Var2, fill=value)) + geom_tile(color = "brown") + scale_fill_gradient(low = "white", high = "steelblue", breaks = c(1, 0)) + guides(fill=guide_legend(title="")) + theme_classic() + xlab("Variable") + ylab("Variable") + scale_x_continuous(breaks = seq(1, ncol(disc$data), 2)) + scale_y_continuous(breaks = seq(1, ncol(disc$data), 2)) + ggtitle("TRUE Graph for covariate level 1") + theme(plot.title = element_text(hjust = 0.5)))

# covariate level 1, CS
(ggplot(reshape2::melt(incl.probs.disc_CS1), aes(x=Var1, y=Var2, fill=value)) + geom_tile(color = "brown") + scale_fill_gradient(low = "white", high = "steelblue", breaks = c(1, 0)) + labs(fill="Probability of Inclusion") + theme_classic() + xlab("Variable") + ylab("Variable") + ggtitle("Inclusion probabilities, covariate level 1, CS") + theme(plot.title = element_text(hjust = 0.5)))

# covariate level 1, grid
(ggplot(reshape2::melt(incl.probs.disc_grid1), aes(x=Var1, y=Var2, fill=value)) + geom_tile(color = "brown") + scale_fill_gradient(low = "white", high = "steelblue", breaks = c(1, 0)) + labs(fill="Probability of Inclusion") + theme_classic() + xlab("Variable") + ylab("Variable") + ggtitle("Inclusion probabilities, covariate level 1, grid") + theme(plot.title = element_text(hjust = 0.5)))

# true graph, covariate level 2
(ggplot(reshape2::melt(true.graph2), aes(x=Var1, y=Var2, fill=value)) + geom_tile(color = "brown") + scale_fill_gradient(low = "white", high = "steelblue", breaks = c(1, 0)) + guides(fill=guide_legend(title="")) + theme_classic() + xlab("Variable") + ylab("Variable") + scale_x_continuous(breaks = seq(1, ncol(disc$data), 2)) + scale_y_continuous(breaks = seq(1, ncol(disc$data), 2)) + ggtitle("TRUE Graph for covariate level 2") + theme(plot.title = element_text(hjust = 0.5)))

# covariate level 2, CS
(ggplot(reshape2::melt(incl.probs.disc_CS2), aes(x=Var1, y=Var2, fill=value)) + geom_tile(color = "brown") + scale_fill_gradient(low = "white", high = "steelblue", breaks = c(1, 0)) + labs(fill="Probability of Inclusion") + theme_classic() + xlab("Variable") + ylab("Variable") + ggtitle("Inclusion probabilities, covariate level 2, CS") + theme(plot.title = element_text(hjust = 0.5)))

# covariate level 2, grid
(ggplot(reshape2::melt(incl.probs.disc_grid2), aes(x=Var1, y=Var2, fill=value)) + geom_tile(color = "brown") + scale_fill_gradient(low = "white", high = "steelblue", breaks = c(1, 0)) + labs(fill="Probability of Inclusion") + theme_classic() + xlab("Variable") + ylab("Variable") + ggtitle("Inclusion probabilities, covariate level 2, grid") + theme(plot.title = element_text(hjust = 0.5)))
```
