// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// grid_search_c
Rcpp::List grid_search_c(const arma::colvec& y, const arma::mat& D, const arma::mat& X_mat, const arma::mat& mu_mat, const arma::mat& alpha_mat, const arma::mat& sigmasq_vec, bool update_sigmasq, const arma::mat& sigmabeta_sq_vec, bool update_sigmabetasq, const arma::colvec& pi_vec, double tolerance, int max_iter, double upper_limit);
RcppExport SEXP _covdepGE_grid_search_c(SEXP ySEXP, SEXP DSEXP, SEXP X_matSEXP, SEXP mu_matSEXP, SEXP alpha_matSEXP, SEXP sigmasq_vecSEXP, SEXP update_sigmasqSEXP, SEXP sigmabeta_sq_vecSEXP, SEXP update_sigmabetasqSEXP, SEXP pi_vecSEXP, SEXP toleranceSEXP, SEXP max_iterSEXP, SEXP upper_limitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_mat(X_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mu_mat(mu_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha_mat(alpha_matSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigmasq_vec(sigmasq_vecSEXP);
    Rcpp::traits::input_parameter< bool >::type update_sigmasq(update_sigmasqSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigmabeta_sq_vec(sigmabeta_sq_vecSEXP);
    Rcpp::traits::input_parameter< bool >::type update_sigmabetasq(update_sigmabetasqSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type pi_vec(pi_vecSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type upper_limit(upper_limitSEXP);
    rcpp_result_gen = Rcpp::wrap(grid_search_c(y, D, X_mat, mu_mat, alpha_mat, sigmasq_vec, update_sigmasq, sigmabeta_sq_vec, update_sigmabetasq, pi_vec, tolerance, max_iter, upper_limit));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_covdepGE_grid_search_c", (DL_FUNC) &_covdepGE_grid_search_c, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_covdepGE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
