# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cavi_c <- function(y, D, X_mat, mu_mat, alpha_mat, sigmasq, sigmabeta_sq, pi_est, tolerance, max_iter, upper_limit = 9) {
    .Call(`_covdepGE_cavi_c`, y, D, X_mat, mu_mat, alpha_mat, sigmasq, sigmabeta_sq, pi_est, tolerance, max_iter, upper_limit)
}

grid_search_c <- function(y, D, X_mat, mu_mat, alpha_mat, sigmasq_vec, sigmabeta_sq_vec, pi_vec, tolerance, max_iter, upper_limit = 9) {
    .Call(`_covdepGE_grid_search_c`, y, D, X_mat, mu_mat, alpha_mat, sigmasq_vec, sigmabeta_sq_vec, pi_vec, tolerance, max_iter, upper_limit)
}

