# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

grid_search_c <- function(y, D, X_mat, mu_mat, alpha_mat, sigmasq_vec, update_sigmasq, sigmabeta_sq_vec, update_sigmabetasq, pi_vec, tolerance, max_iter, upper_limit = 9) {
    .Call(`_covdepGE_grid_search_c`, y, D, X_mat, mu_mat, alpha_mat, sigmasq_vec, update_sigmasq, sigmabeta_sq_vec, update_sigmabetasq, pi_vec, tolerance, max_iter, upper_limit)
}

