# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cov_vsvb_c <- function(y, D, X_mat, mu_mat, alpha_mat, sigmasq, sigmabeta_sq, pi_est, tolerance = 1e-9, max_iter = 100L, upper_limit = 9) {
    .Call(`_covdepGE_cov_vsvb_c`, y, D, X_mat, mu_mat, alpha_mat, sigmasq, sigmabeta_sq, pi_est, tolerance, max_iter, upper_limit)
}

sigma_loop_c <- function(y, D, X_mat, mu_mat, alpha_mat, sigmasq, sigmabeta_sq_vec, pi_est, tolerance = 1e-9, max_iter = 100L, upper_limit = 9) {
    .Call(`_covdepGE_sigma_loop_c`, y, D, X_mat, mu_mat, alpha_mat, sigmasq, sigmabeta_sq_vec, pi_est, tolerance, max_iter, upper_limit)
}

